Project_MVC/Models/AlbumsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

using ChinookEntities;
using ChinookContext;

namespace Project_MVC.Models
{
    public class AlbumsViewModel
    {
        public string Heading { get; set; }
        public string orderedBy{ get; set; }
        public string searchString{ get; set; }
        public List<Album> Albums { get; set; } 
        public List<Artist> Artists { get; set; }
        public Album Album { get; set; }

        /* Tracks */

        public string trackHeading { get; set; }
        public List<Track> Tracks { get; set; }
        public Track Track { get; set; }
        
    }
}

Project_MVC/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

using Project_MVC.Models;

using ChinookEntities;
using ChinookContext;

namespace Project_MVC.Controllers
{
    public class AlbumsController : Controller
    {
        public IActionResult Index()
        {
            AlbumsViewModel model = new AlbumsViewModel();
            ChinookDatabase db = new ChinookDatabase();
            model.Heading = "Chinook Album Information";
            model.Albums = db.Albums.Include(ar => ar.Artist).ToList();
            return View(model);
        }
        public IActionResult InsertPage()
        {
            AlbumsViewModel model = new AlbumsViewModel();
            ChinookDatabase db = new ChinookDatabase();
            model.Heading = "Insert a New Album";
            model.Artists = db.Artists.ToList();
            return View(model);
        }
        public IActionResult Insert(string Title, short ArtistId, List<string> Tracks)
        {
            ChinookDatabase db = new ChinookDatabase();
            Album newAlbum = new Album
            {
                Title = Title,
                ArtistId = ArtistId
            };
            db.Albums.Add(newAlbum);
            db.SaveChanges();

            if (Tracks != null)
            {
                foreach (string trackName in Tracks)
                {
                    if (!string.IsNullOrEmpty(trackName))
                    {
                        Track newTrack = new Track
                        {
                            AlbumId = newAlbum.AlbumId,
                            Name = trackName,
                            MediaTypeId = 1,
                            GenreId = 1,
                            Composer = "TBD",
                            Milliseconds = 1111,
                            UnitPrice = 0.99
                        };
                        db.Tracks.Add(newTrack);
                    }
                }
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult updateForm(string id)
        {
            AlbumsViewModel model = new AlbumsViewModel();
            ChinookDatabase db = new ChinookDatabase();
            var albumTitle = db.Albums.Where(al => al.AlbumId == Int32.Parse(id)).Select(al => al.Title).FirstOrDefault();
            model.Heading = $"Update | '{albumTitle}'";
            model.Album = db.Albums.Include(ar => ar.Artist).FirstOrDefault(al => al.AlbumId == Int32.Parse(id));
            if (@model.Album == null)
            {
                return RedirectToAction("Index");
            }
            model.Tracks = db.Tracks.Where(a => a.AlbumId == Int32.Parse(id)).ToList();

            return View(model);
        }
        public IActionResult Update(string id, string Title, string ArtistName, string[] TrackNames, int[] TrackIds, string NewTrackName)
        {
            ChinookDatabase db = new ChinookDatabase();
            AlbumsViewModel model = new AlbumsViewModel();
            model.Album = db.Albums.Include(ar => ar.Artist).FirstOrDefault(al => al.AlbumId == Int32.Parse(id));
            model.Tracks = db.Tracks.Where(t => t.AlbumId == Int32.Parse(id)).ToList();
            if (@model.Album == null)
            {
                return RedirectToAction("Index");
            }

            // Update album
            if (!string.IsNullOrEmpty(Title) && model.Album.Title != Title)
            {
                model.Album.Title = Title;
            }
            if (!string.IsNullOrEmpty(ArtistName) && model.Album.Artist.Name != ArtistName)
            {
                model.Album.Artist.Name = ArtistName;
            }

            // Update album tracks
            for (int i = 0; i < model.Tracks.Count; i++)
            {
                if (TrackIds != null && i < TrackIds.Length && TrackIds[i] != 0 && !string.IsNullOrEmpty(TrackNames[i]))
                {
                    int trackId = TrackIds[i];
                    Track track = db.Tracks.FirstOrDefault(t => t.TrackId == trackId);
                    if (track != null && track.Name != TrackNames[i])
                    {
                        track.Name = TrackNames[i];
                    }
                }
            }

            // Add new track to album
            if (!string.IsNullOrEmpty(NewTrackName))
            {
                Track newTrack = new Track
                {
                    AlbumId = model.Album.AlbumId,
                    Name = NewTrackName,
                    MediaTypeId = 1,
                    GenreId = 1,
                    Composer = "TBD",
                    Milliseconds = 1111,
                    UnitPrice = 0.99
                };
                db.Tracks.Add(newTrack);
            }
            

            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult DeleteSingleTrack(int id)
        {
            ChinookDatabase db = new ChinookDatabase();
            Track track = db.Tracks.FirstOrDefault(t => t.TrackId == id);
            var playlistTracksToDelete = db.Playlist_Tracks.Where(pt => pt.TrackId == track.TrackId).ToList();
            db.Playlist_Tracks.RemoveRange(playlistTracksToDelete);

            var invoiceItemsToDelete = db.invoice_Items.Where(ii => ii.TrackId == track.TrackId).ToList();
            db.invoice_Items.RemoveRange(invoiceItemsToDelete);

            if (track != null)
            {
                db.Tracks.Remove(track);
                db.SaveChanges();
            }
            return RedirectToAction("UpdateForm", new { id = track.AlbumId });
        }
        public IActionResult deletePage(string id)
        {
            AlbumsViewModel model = new AlbumsViewModel();
            ChinookDatabase db = new ChinookDatabase();
            var albumTitle = db.Albums.Where(al => al.AlbumId == Int32.Parse(id)).Select(al => al.Title).FirstOrDefault();
            var albumArtist = db.Albums.Where(al => al.AlbumId == Int32.Parse(id)).Select(al => al.Artist.Name).FirstOrDefault();
            model.trackHeading = $"'{albumTitle}' ({albumArtist})";
            model.Tracks = db.Tracks.Where(a => a.AlbumId == Int32.Parse(id)).ToList();
            model.Track = db.Tracks.FirstOrDefault(a => a.AlbumId == Int32.Parse(id));

            return View(model);
        }
        public IActionResult Delete(string id)
        {
            ChinookDatabase db = new ChinookDatabase();
            var tracksToDelete = db.Tracks.Where(t => t.AlbumId == Int32.Parse(id)).ToList();
            foreach (var track in tracksToDelete)
            {
                var playlistTracksToDelete = db.Playlist_Tracks.Where(pt => pt.TrackId == track.TrackId).ToList();
                db.Playlist_Tracks.RemoveRange(playlistTracksToDelete);
            }

            foreach (var track in tracksToDelete)
            {
                var invoiceItemsToDelete = db.invoice_Items.Where(ii => ii.TrackId == track.TrackId).ToList();
                db.invoice_Items.RemoveRange(invoiceItemsToDelete);
            }
          
            db.Tracks.RemoveRange(tracksToDelete);

            Album delAlbum = db.Albums.Single(al => al.AlbumId == Int32.Parse(id));
            db.Albums.Remove(delAlbum);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Search(string searchText)
        {
            ChinookDatabase db = new ChinookDatabase();
            AlbumsViewModel model = new AlbumsViewModel();
            if (string.IsNullOrEmpty(searchText))
            {
                model.searchString = "No results";
                model.Albums = db.Albums.Include(ar => ar.Artist).ToList();
            }
            else
            {
                model.searchString = $"Search results for '{searchText}'";
                model.Albums = db.Albums.Where(a => a.Title.Contains(searchText)
                || a.Artist.Name.Contains(searchText)).Include(ar => ar.Artist).ToList();
            }

            return View(model);
        }
        public IActionResult Order()
        {
            AlbumsViewModel model = new AlbumsViewModel();
            ChinookDatabase db = new ChinookDatabase();
            var sortType = Request.Form["orderBy"];
            if (sortType == "T_ASC")
            {
                model.Albums = db.Albums.Include(ar => ar.Artist).OrderBy(t => t.Title).ToList();
                model.orderedBy = "Albums Ascending Order [A-Z]";
            }
            else if (sortType == "T_DESC")
            {
                model.Albums = db.Albums.Include(ar => ar.Artist).OrderByDescending(t => t.Title).ToList();
                model.orderedBy = "Albums Descending Order [Z-A]";
            }
            else if (sortType == "A_ASC")
            {
                model.Albums = db.Albums.Include(ar => ar.Artist).OrderBy(an => an.Artist.Name).ToList();
                model.orderedBy = "Artists Ascending Order [Z-A]";
            }
            else if (sortType == "A_DESC")
            {
                model.Albums = db.Albums.Include(ar => ar.Artist).OrderByDescending(an => an.Artist.Name).ToList();
                model.orderedBy = "Artists Descending Order [Z-A]";
            }
            return View(model);
        }
    }
}

Project_MVC/Views/Albums/Index.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
    <style>
        td,
        th {
            padding: 5px;
        }

        #details {
            padding: 5px;
        }
    </style>
</head>


<body>
    <h1>@Model.Heading</h1>

    <br>

    <a asp-action="InsertPage">Insert Album</a>

    <br>

    <form method="get" asp-action="Search">
        <input type="text" name="searchText" placeholder="Enter an album title...">
        <input type="submit" class="btn-primary" value="Search">
    </form>

    <br>

    <form method="post" asp-action="Order">
        <label for="orderBy">Order by:</label>
        <select name="orderBy">
            <option value="">-- Select an option --</option>
            <option value="T_ASC">Album Title ASC</option>
            <option value="A_ASC">Artist Name ASC</option>
            <option value="T_DESC">Album Title DESC</option>
            <option value="A_DESC">Artist Name DESC</option>
        </select>
        <input type="submit" class="btn-primary" value="Order">
    </form>

    <br>

    <table border="1">
        <tr>
            <th>Album ID</th>
            <th>Album Title</th>
            <th>Album Artist</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>

        @foreach (Album album in @Model.Albums)
        {
            <tr>
                <td>@album.AlbumId</td>
                <td><a id="details" class="btn-primary" href="~/Tracks/Index/@album.AlbumId">@album.Title</a></td>
                <td>@Html.DisplayFor(artist => album.Artist.Name)</td>
                <td>
                    <form method="post" asp-action="updateForm">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@album.AlbumId" />
                        <input type="submit" class="btn-primary" value="Update">
                    </form>
                </td>
                <td>
                    <form method="post" asp-action="deletePage">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@album.AlbumId" />
                        <input type="submit" value="Delete" class="btn btn-danger" id="delete">
                    </form>
                </td>
            </tr>
        }
    </table>
</body>

</html>

Project_MVC/Views/Albums/InsertPage.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
</head>

<body>
    <h1>@Model.Heading</h1>

    <br>

    <form method="post" asp-action="Insert">
        @Html.AntiForgeryToken()
        <label for="Title">Album:</label>
        <input type="text" name="Title">
        <br>
        <label for="ArtistId">Artist:</label>
        <select name="ArtistId" id="ArtistId">
            <option value="">-- Enter an Artist --</option>
            @foreach (Artist artist in Model.Artists)
            {
                <option value="@artist.ArtistId">@artist.Name</option>
            }
        </select>
        <br>
        <div id="tracks-container">
            <div class="track">
                <label for="TrackName">Track 1:</label>
                <input type="text" name="Tracks[0]" class="track-input">
                <button type="button" class="delete-track-btn">Delete Track</button>
                <br>
            </div>
        </div>
        <button type="button" class="btn-primary" id="add-track-btn">Add a Track</button>
        <br><br>
        <input type="submit" class="btn-primary" value="Insert">
    </form>
    <br>
    <a href="~/Albums/Index">Back</a>
</body>

<script>
    let trackNum = 2;
    const trackInputsDiv = document.getElementById("tracks-container");

    function addTrackInput() {
        const newTrackInput = document.createElement("div");
        newTrackInput.innerHTML = `
            <label for="TrackName">Track ${trackNum}:</label>
            <input type="text" name="Tracks[${trackNum - 1}]" class="track-input">
            <button type="button" class="delete-track-btn">Delete Track</button>
            <br>
        `;
        trackInputsDiv.appendChild(newTrackInput);
        trackNum++;
    }

    trackInputsDiv.addEventListener("click", function (event) {
        if (event.target.classList.contains("delete-track-btn")) {
            event.target.parentNode.remove();
            trackNum--;
        }
    });

    document.getElementById("add-track-btn").addEventListener("click", addTrackInput);
</script>

</html>

Project_MVC/Views/Albums/Order.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
    <style>
        td, th {
            padding: 5px;
        }

        #details {
            padding: 5px;
        }
    </style>
</head>

<body>
    <h1>@Model.orderedBy</h1>

    <br>
    <hr>
    <br>

    <table border="1">
        <tr>
            <th>Album ID</th>
            <th>Album Title</th>
            <th>Album Artist</th>
        </tr>

        @foreach (Album album in @Model.Albums)
        {
            <tr>
                <td>@album.AlbumId</td>
                <td><a class="btn-primary" id="details" href="~/Tracks/Index/@album.AlbumId">@album.Title</a></td>
                <td>@Html.DisplayFor(artist => album.Artist.Name)</td>
            </tr>
        }
    </table>
    <a href="~/Albums/Index">Back</a>
</body>

</html>

Project_MVC/Views/Albums/Search.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
    <style>
        td,
        th {
            padding: 5px;
        }
        
        #details {
            padding: 5px;
        }
    </style>
</head>

<body>
    <h1>@Model.searchString</h1>

    <br>
    <hr>
    <br>

    @if (Model.Albums == null || @Model.Albums.Count == 0)
    {
        <p>No results found.</p>
    }
    else
    {
        <table border="1">
            <tr>
                <th>Album ID</th>
                <th>Album Title</th>
                <th>Album Artist</th>
            </tr>

            @foreach (Album album in @Model.Albums)
            {
                <tr>
                    <td>@album.AlbumId</td>
                    <td><a class="btn-primary" id="details" href="~/Tracks/Index/@album.AlbumId">@album.Title</a></td>
                    <td>@Html.DisplayFor(artist => album.Artist.Name)</td>
                </tr>
            }
        </table>
    }
</body>
<a href="~/Albums/Index">Back</a>

</html>

Project_MVC/Views/Albums/deletePage.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
    <style>
        td,
        th {
            padding: 5px;
        }

        #delete {
            background-color: red;
            color: #fff;
        }

        #details {
            padding: 5px;
        }
    </style>
</head>

<body>
    <h1>@Model.trackHeading</h1></br> 

    <br>
    <hr>
    <br>
    
    <form method="post" asp-action="Delete">
        @Html.AntiForgeryToken()
        <p>Are you sure you want to remove this album?</p>
        <input type="hidden" name="id" value="@Model.Track.AlbumId" />
        <input type="submit" value="Yes, Delete" id="delete" new {
            onclick="return confirm('Are you sure you want to delete this album?')" }>
    </form></br>

    <hr>

    <ol>
        @foreach (Track track in @Model.Tracks)
        {
            <li>@track.Name</li>
        }
    </ol>

    <a href="~/Albums/Index">Back</a>
</body>

</html>

Project_MVC/Views/Albums/updateForm.cshtml
@model AlbumsViewModel
@using ChinookEntities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chinook Web App</title>
</head>

<body>
    <h1>@Model.Heading</h1>
    <br>
    <form method="post" asp-action="Update">
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@Model.Album.AlbumId">
        <label for="Title">Album:</label>
        <input type="text" name="Title" value="@Model.Album.Title">
        <br>
        <label for="ArtistName">Artist:</label>
        <input type="text" name="ArtistName" value="@Model.Album.Artist.Name">
        <br>
        @{
            var counter = 0;
        }
        @foreach (Track track in Model.Tracks)
        {
            counter++;
            <label for="TrackName@counter">Track @counter:</label>
            <input type="text" name="TrackNames[]" value="@track.Name">
            <input type="hidden" name="TrackIds[]" value="@track.TrackId">
            <button type="button" onclick="deleteTrack(@track.TrackId)">Delete</button>
            <br>
        }
        <hr>
        <label for="NewTrackName">New Track:</label>
        <input type="text" name="NewTrackName">
        <input type="submit" class="btn-primary" value="Update">
    </form>

    <a href="~/Albums/Index">Back</a>
</body>

<script>
    function deleteTrack(trackId) {
    if (confirm("Are you sure you want to delete this track?")) {
        window.location.href = '@Url.Action("DeleteSingleTrack", "Albums")' + "?id=" + trackId;
    }
}
</script>

</html>